[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
maxUploadSize=50
enableXsrfProtection=true
enableCORS=false

[browser]
gatherUsageStats=false

[runner]
fastReruns=true

[client]
showErrorDetails=true
toolbarMode="minimal"

[logger]
level="error" 